### PR TITLE
Jest Setup

### PR DESCRIPTION
**Pull request by akoushke**
rebased of the PR https://github.com/webex/component-adapter-interfaces/pull/2

### CODE REVIEW

**Comment by adamweeks** [comment]
Can you add `test_results` to the gitignore?

**Comment by akoushke** [comment]
> Can you add `test_results` to the gitignore?

it's included @adamweeks

**Comment by adamweeks** [comment]
> > Can you add `test_results` to the gitignore?
> 
> it's included @adamweeks

@akoushke 
img

**Pull request merged**
