### PR TITLE
feat(MembershipsAdapter): add boolean property "guest" to the Member interface

### PR DESCRIPTION
**Pull request by BenjaminGolya**
Add guest property for the Member interface.

https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-222984

### CODE REVIEW

**Review by lalli-flores — APPROVED** [review]
@BenjaminGolya, this looks good. If you could fix the conflicts we can go ahead and merge.

**Comment by lalli-flores** [comment]
@BenjaminGolya, seems like something went wrong with the rebase and files that shouldn't be modified are showing as so

**Comment by BenjaminGolya** [comment]
> @BenjaminGolya, seems like something went wrong with the rebase and files that shouldn't be modified are showing as so

I fixed the rebase.

**Review by lalli-flores — APPROVED** [review]

**Pull request merged**
